services:
    app:
        build:
            args:
                user: taskflow
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: taskflow-api
        container_name: taskflow-api
        restart: no
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - taskflow
        depends_on:
            - database

    webserver:
        image: nginx:alpine
        container_name: taskflow-webserver
        restart: no
        tty: true
        ports:
            - '8085:80'
        networks:
            - taskflow
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        depends_on:
            - app



    database:
        image: mysql:8.0
        container_name: taskflow-mysql
        restart: no
        tty: true
        ports:
            - '3312:3306'
        privileged: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - taskflow
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql:/backup

    mailer:
        image: maildev/maildev
        container_name: taskflow-mailer
        restart: no
        ports:
            - '1083:1080'
            - '1028:1025'
        networks:
            - taskflow

networks:
    taskflow:
        driver: bridge
        external: true
    proxy:
        external: true

volumes:
    dbdata:
        driver: local
